---
.rubocop.yml:
  profiles:
    strict:
      configs:
        AllCops:
          TargetRubyVersion: '2.2'
          Include:
          - "lib/*/*/*/*.rb"
          - "tasks/*.rb"
          - "lib/*/*/*.rb"
        Lint/ScriptPermission:
          Enabled: false
        Style/NestedTernaryOperator:
          Enabled: false
        Layout/EmptyLines:
          Enabled: false
        Layout/EmptyLineBetweenDefs:
          Enabled: false
        Metrics/LineLength:
          Enabled: false
        Lint/UnusedBlockArgument:
          Enabled: false
        Style/Semicolon:
          Enabled: false
        Style/MultilineIfModifier:
          Enabled: false
        Style/EachWithObject:
          Enabled: false
        Style/TrailingCommaInHashLiteral:
          Enabled: false
        Style/TrailingCommaInArguments:
          Enabled: false
        Layout/EmptyLinesAroundMethodBody:
          Enabled: false
        Style/RedundantSelf:
          Enabled: false
        Style/HashSyntax:
          Enabled: false
        Lint/Void:
          Enabled: false
        Style/RedundantReturn:
          Enabled: false
        Layout/IndentationConsistency:
          Enabled: false

.gitlab-ci.yml:
  delete: true

appveyor.yml:
  delete: true

.travis.yml:
  delete: true